-- AlterTable
ALTER TABLE "Booking" ADD COLUMN "subtotal" DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE "Booking" ADD COLUMN "serviceFee" DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE "Booking" ADD COLUMN "discount" DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE "Booking" ADD COLUMN "taxRate" DECIMAL(5,2) NOT NULL DEFAULT 0.15;
ALTER TABLE "Booking" ADD COLUMN "taxAmount" DECIMAL(10,2) NOT NULL DEFAULT 0.00;

-- AlterTable
ALTER TABLE "HotelPolicy" ADD COLUMN "taxRate" DECIMAL(5,2) NOT NULL DEFAULT 0.15;
