import type { Room } from '../types';

export type RootStackParamList = {
  Auth: { initialMode?: 'login' | 'register' } | undefined;
  MainTabs: undefined;
  Search: undefined;
  HotelDetail: { hotelId: string };
  RoomDetail: { room: Room; hotelName: string; hotelId: string; checkIn: string; checkOut: string; hotelImages?: { id: string; url: string; isPrimary: boolean }[]; guests?: { adults: number; children: number } };
  BookingFlow: {
    hotelId: string;
    roomId: string;
    hotelName?: string;
    roomType?: string;
    roomCapacity?: number;
    checkIn?: string;
    checkOut?: string;
    promoCode?: string;
  };
  MockAuth: {
    bookingId: string;
    method: string;
    amount: number;
    currency?: string;
    hotelName: string;
    reference: string;
  };
  PaymentHistory: undefined;
  BookingDetail: { bookingId: string };
  Review: { hotelId: string; hotelName: string; bookingId?: string; mode?: 'create' | 'edit'; existingReview?: { id: string; rating: number; comment: string } | null };
  ForgotPassword: undefined;
  VerifyEmail: { token: string };
  ResetPassword: { token: string };
  Notifications: undefined;
  MyReviews: undefined;
  AdminOverview: undefined;
  AdminUsers: undefined;
  AdminHotels: undefined;
  AdminBookings: undefined;
  AdminPayments: undefined;
  AdminCoupons: undefined;
  AdminReviews: undefined;
  AdminReports: undefined;
  AdminSettings: undefined;
  AdminAuditLog: undefined;
  ManagerOverview: undefined;
  ManagerBookings: undefined;
  ManagerBilling: undefined;
  ManagerHotel: undefined;
  ManagerRooms: undefined;
  ManagerReports: undefined;
  ManagerMore: undefined;
  BookingModify: { bookingId: string };
  Disputes: undefined;
  DisputeDetail: { disputeId: string };
  ContactInbox: undefined;
  ContactThread: { threadId: string };
  ContactNew: { hotelId?: string };
  AdminStaffHotels: undefined;
  AdminDisputes: undefined;
  AdminEmergency: undefined;
  AdminFeatureFlags: undefined;
  WalkInBooking: undefined;
  EarlyCheckinLateCheckout: { bookingId: string; mode: 'early-checkin' | 'late-checkout' };
  ChapaCheckout: {
    bookingId: string;
    method: string;
    amount: number;
    currency?: string;
    hotelName: string;
    roomType?: string;
    phone?: string;
  };
  TelebirrOtp: {
    bookingId: string;
    amount: number;
    currency?: string;
    hotelName: string;
    phone: string;
  };
  BankAuth: {
    bookingId: string;
    paymentId: string;
    amount: number;
    currency?: string;
    hotelName: string;
    method: string;
    bankCode: string;
    cbeReference?: string;
  };
  PaymentResult: {
    bookingId: string;
    status: 'SUCCEEDED' | 'FAILED' | 'PROCESSING' | 'CANCELLED' | 'UNKNOWN';
    amount: number;
    currency?: string;
    hotelName: string;
    method: string;
    reference: string;
  };
  MockSmsInbox: undefined;
  Splash: undefined;
  Settings: undefined;
  Help: undefined;
  Onboarding: undefined;
  AccountSecurity: undefined;
};

export type TabParamList = {
  HomeTab: undefined;
  BookingsTab: undefined;
  FavoritesTab: undefined;
  ProfileTab: undefined;
};
